spring:
  datasource:
    url: jdbc:mysql://192.168.177.128:3306/security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver